# Generated by Django 5.1.7 on 2025-04-02 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("representative_app", "0002_alter_reseller_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResellerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "reseller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reseller_notifications",
                        to="representative_app.reseller",
                    ),
                ),
            ],
            options={
                "db_table": "reseller_notifications",
            },
        ),
    ]
