# Generated by Django 5.1.7 on 2025-04-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("image_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("en_country_name", models.CharField(max_length=50)),
                ("fa_country_name", models.CharField(max_length=50)),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "country_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="image_app.images",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                ("service_name", models.CharField(max_length=255)),
                ("is_publish", models.BooleanField(default=True)),
                (
                    "server_type",
                    models.CharField(
                        choices=[
                            ("dedicated", "اختصاصی"),
                            ("shared", "اشتراکی"),
                            ("fast", "پر سرعت"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        limit_choices_to={"is_publish": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="server_app.country",
                    ),
                ),
            ],
            options={
                "db_table": "service",
            },
        ),
    ]
