# Generated by Django 5.1.7 on 2025-04-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("image_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reseller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="نام شرکت/نماینده"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="تلفن تماس"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="ایمیل"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(verbose_name="حداکثر کاربران مجاز"),
                ),
                (
                    "can_create_servers",
                    models.BooleanField(default=False, verbose_name="اجازه ایجاد سرور"),
                ),
                (
                    "allowed_countries",
                    models.JSONField(
                        default=list,
                        help_text="لیست کشورهایی که این نماینده می\u200cتواند سرور ارائه دهد.",
                        verbose_name="کشورهای مجاز برای فروش",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4a6bff", max_length=7, verbose_name="رنگ اصلی پنل"
                    ),
                ),
                (
                    "custom_welcome_message",
                    models.TextField(
                        blank=True, verbose_name="پیام خوش\u200cآمدگویی اختصاصی"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        verbose_name="درصد کمیسیون (%)",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="موجودی (ریال)",
                    ),
                ),
                (
                    "custom_logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="image_app.images",
                        verbose_name="لوگوی اختصاصی",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reseller",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "نماینده فروش",
                "verbose_name_plural": "نمایندگان فروش",
                "db_table": "reseller",
            },
        ),
    ]
