# Generated by Django 5.1.7 on 2025-04-03 10:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(editable=False, null=True)),
                ("deleted_at", models.DateTimeField(editable=False, null=True)),
                (
                    "volume_choice",
                    models.CharField(
                        choices=[("mg", "Mg"), ("gb", "Gb"), ("tra", "Tra")],
                        default="gb",
                        max_length=7,
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="کاربر چقدر حجم داشته باشد",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_inf_volume",
                    models.BooleanField(
                        default=False, help_text="ایا حجم کاربر نامحدود باشد!"
                    ),
                ),
                (
                    "start_premium",
                    models.DateField(
                        blank=True,
                        help_text="تاریخ شروع اشتراک اگر کاربر لاگین کند اشتراک کاربر از همان روز شروع خواهد شد",
                        null=True,
                    ),
                ),
                (
                    "number_of_days",
                    models.PositiveIntegerField(
                        default=0, help_text="تعداد روز", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
