# Generated by Django 5.1.7 on 2025-03-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdevice',
            name='device_number',
            field=models.CharField(help_text='سریال گوشی', max_length=255, unique=True),
        ),
    ]
