# Generated by Django 5.1.7 on 2025-04-03 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_inf_volume",
        ),
        migrations.RemoveField(
            model_name="user",
            name="number_of_days",
        ),
        migrations.RemoveField(
            model_name="user",
            name="start_premium",
        ),
        migrations.RemoveField(
            model_name="user",
            name="volume_choice",
        ),
    ]
