# Generated by Django 5.1.7 on 2025-04-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_contentdevice_device_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
