# Generated by Django 5.1.7 on 2025-04-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0003_remove_user_volume_remove_user_volume_usage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
    ]
