# Generated by Django 5.1.7 on 2025-04-03 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0004_remove_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentdevice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contentdevice",
            name="deleted_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="contentdevice",
            name="is_deleted",
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="contentdevice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
